Agregando la tarea 6
VitmiTor/repotareas pull request #1
Opened 2022-08-27 19:29 UTC by VitmiTor

27/08/2022-Tarea6

2022-08-27 19:33 UTC, calvarioTeacher31 requested changes

2022-08-27 19:33 UTC, calvarioTeacher31 commented on pom.xml
> +
espacios muertos

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/main/java/base/BaseTest.java
> +    protected final SoftAssert softAssert = new SoftAssert();
inicializa el soft assert dentro del BeforeMethod del Base TEst mejor

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/main/java/base/BaseTest.java
> +
espacios muertos

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        maestro2.isEsHombre();
qué sentido tiene esto?

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        var nombre2 = maestro2.getNombre();
innecesario crear variables, puedes hacer defrente get en el soft asert, esto aplica para lo de más tests

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        softAssert.assertEquals(codigo1, "PO-01");
declara PO-01 como variable del método y luego lo llamas ya que estás repitiendo esto

2022-08-27 19:33 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        softAssert.assertEquals(especialidad1, "Maestro Pokemon");
cada log y soft assert tienen que ir juntos separados en líneas como bloquecitos, análogamente al scanner.int y la sout para que el usuario escriba

2022-08-27 21:26 UTC, VitmiTor commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        maestro2.isEsHombre();
En la "Tarea 6" especificaba que se debía declarar las variables

2022-08-27 22:18 UTC, VitmiTor commented on pom.xml
> +
corregido

2022-08-27 22:18 UTC, VitmiTor commented on src/main/java/base/BaseTest.java
> +    protected final SoftAssert softAssert = new SoftAssert();
corregido

2022-08-27 22:18 UTC, VitmiTor commented on src/main/java/base/BaseTest.java
> +
corregido

2022-08-27 22:18 UTC, VitmiTor commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        var nombre2 = maestro2.getNombre();
corregido

2022-08-27 22:18 UTC, VitmiTor commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        softAssert.assertEquals(codigo1, "PO-01");
corregido

2022-08-27 22:18 UTC, VitmiTor commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        softAssert.assertEquals(especialidad1, "Maestro Pokemon");
corregido

2022-08-27 22:40 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +
espacio muerto

2022-08-27 22:58 UTC, calvarioTeacher31 commented on src/main/java/Utilities/Logs.java
> +
espacio muerto

2022-08-27 22:58 UTC, calvarioTeacher31 reviewed
a

2022-08-27 23:04 UTC, VitmiTor commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +
ok coregido

2022-08-27 23:04 UTC, VitmiTor commented on src/main/java/Utilities/Logs.java
> +
corregido

2022-08-27 23:05 UTC, calvarioTeacher31 approved these changes

2022-08-27 23:07 UTC, merged

2022-09-01 05:05 UTC, calvarioTeacher31 commented on src/test/java/MaestroPokemonTests/MaestroPokemonTests.java
> +        maestro2.isEsHombre();
se refería a declarar el get en la clase de maestro